---
- name: Restart nginx when down
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Test webhook
      condition: event.payload.alerts[0].labels.alertname == "NginxDown"
      actions:
        - debug:
            msg: "Received NginxDown webhook"
